AWSTemplateFormatVersion: 2010-09-09
Description: Field Day demo application CloudFormation template

Parameters:
  VPC:
    Description: Id of existing VPC
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: Must be a valid VPC Id
  Subnet:
    Description: Id of existing public Subnet
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: Must be a valid Subnet Id
  AMI:
    Description: AMI to launch instance with
    Type: AWS::EC2::Image::Id
    ConstraintDescription: Must be a valid AMI

Resources:
  FieldDayInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType:  t2.micro
      KeyName: fieldday
      SecurityGroupIds:
        - !GetAtt FieldDaySecurityGroup.GroupId
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: fieldday-cf

  FieldDaySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 3000
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 3000
          IpProtocol: tcp
          ToPort: 3000
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: -1
          ToPort: -1

  FieldDayElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref FieldDayInstance
